= System Scope and Context
:page-partial:
:plantuml-server-url: http://plantuml.com/plantuml

[.helptext]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.
****

== Business Context

[.helptext]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

[plantuml, system-context-business, png]
....
skinparam monochrome true
title Home Entertainment - System Context
footer ACME Inc. %date[yyyy]%

component "Home Entertainment" as system

actor Owner
actor Viewer
node Manufacturer
node "TV broadcast" as broadcast

system -down- Owner
system -down- Viewer
system -up- Manufacturer
system -up- "TV broadcast" as broadcast
....

.System actors
[options="header"]
|===
| Actor | Description
| Manufacturer | The manufacturer of the hardware may update firmware without interaction of the device owner
| Owner | The owner controls the home entertainment system via various controls
| Viewer | Audio and visual information from the system is consumed by the Viewer (which may be identical to the _Owner_)
| TV Broadcast | TV content is distributed to the system via a broadcasting service over Satellite
|===

== Technical Context

[.helptext]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****


[plantuml, system-context-technical, png]
....
skinparam monochrome true
title Home Entertainment - Technical System Context
footer ACME Inc. %date[yyyy]%

component "Home Entertainment" as system

interface "Remote Control" as rc
interface WAN
interface LAN
interface Audio
interface Video
interface Satellite

WAN )-down- system
rc -down- system
LAN -down- system
Audio -up- system
Video -up- system
Satellite )-down- system
....

.Technical Interfaces
[options="header"]
|===
| Interface | Description | I/O
| Audio | The system generates audio information and outputs it via speakers to the _Owner_ | out:Soundwaves
| Video | Visual information is tranferred to the _Owner_ | out:Light
| LAN | Local area network connection is used for communication between the Owner and the system | in:media control
| WAN | An internet connection is used by the system to update its firmware via the _Manufacturer_ or to fetch online content | out:HTTPS
| Remote Control | A remote control is used by the _Owner_ to modify the system state | in:physical interaction
| Satellite | Using the `DVB-S` standard television program from the TV broadcast is received | in:DVB-S
|===
