= Runtime View
:page-partial:

[.helptext]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

== Show TV channel

In the basic use case of watching a TV channel the media manager simply forwards content from the satellite to the AV component.

[plantuml, runtime-tv-channel, png]
----
@startuml
skinparam monochrome true
participant "Media Manager" as mediaman
participant "AV component" as av
participant "Speaker" as speaker
participant LCD

mediaman -> av: media stream
av -> speaker: audio stream
av -> LCD: video stream
@enduml
----

== Update software

An available update of the system software on manufacturer servers is de-coupled into software download and software installation. After a successful download the Owner is informed about an update possibility and waits for his input.

[plantuml, runtime-update-sw, png]
----
@startuml
skinparam monochrome true
participant Manufacturer
participant "Media Manager" as mediaman
participant "AV component" as av
participant LCD
participant Owner

mediaman -> Manufacturer: GET device software status
mediaman <-- Manufacturer: new software version available
mediaman -> Manufacturer: download new software
mediaman <-- Manufacturer
mediaman -> av: overlay update info
av -> LCD++: display update info
LCD --> Owner: inform owner of update
Owner -> mediaman: perform update
mediaman -> mediaman: install update on self
mediaman -> av: remove update overlay
av -> LCD--: show raw media feed onlyk
@enduml
----

== <Runtime Scenario n>
