:page-partial:
== Deployment View

=== Infrastructure Level 1

****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

_**<Overview Diagram>**_

Motivation::

_<explanation in text form>_

Quality and/or Performance Features::

_<explanation in text form>_

Mapping of Building Blocks to Infrastructure::
_<description of the mapping>_


=== Infrastructure Level 2

****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_
