= Quality Requirements
:page-partial:
:plantuml-server-url: http://plantuml.com/plantuml

[.helptext]
****
.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

== Quality Tree

[.helptext]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.
****

The following diagram shows the weighted **SQuaRE** model of ISO25010 (_Systems and software Quality Requirements and Evaluation - System and software quality models_).

[plantuml, quality-model, png]
----
skinparam monochrome true
skinparam defaulttextalignment center
skinparam legendbackgroundcolor none
hide circle
package "<b>ISO25010\nQuality Model" as iso <<Rectangle>> {

}

class Usability {
  approriateness
  <strike>recognisability
  <b>learnability
  <b>operatibility
  <strike>user error protection
  <b>UI aesthetics
  <b>accessibility
}

class Reliability {
  <strike>maturity
  <strike>availability
  fault tolerance
  <strike>recoverability
}

class Security {
  <strike>confidentiality
  integrity
  <strike>non-repudiation
  <strike>accountability
  <strike>authenticity
}

class Maintainability {
  <strike>modularity
  <strike>reusability
  <strike>analysability
  <strike>modifiability
  <strike>testability
}

class Portability {
  <strike>adaptability
  installability
  <strike>replaceability
}

class "Functional Suitability" as fs {
  completeness
  <strike>correctness
  <strike>appropriateness
}

class "Performance Efficiency" as pe {
  <strike>time-behaviour
  <strike>resource utilisation
  <strike>capacity
}

class Compatibility {
  <strike>co-existence
  interoperability
}

iso -down- Compatibility
iso -down- pe
iso -down- fs
iso -up- Portability
iso -up- Security
iso -up- Maintainability
iso -left- Reliability
iso -right- Usability

legend right
|Style| Relevance |
|<b>bold| in focus |
|<strike>striked| irrelevant |
|default| considered |
endlegend
----

The main focus of the system lies on **Usability** by the _Owner_ and _Viewer_.
Security aspects are relevant to the extent that neither the system integrity nor the Owners privacy may be compromised.
The third category of important quality attributes concerns the compatibility of the entire system that should allow easy installation and a certain degree of fault tolerance towards errors in individual system components.

As the system is a consumer good with relatively short lifespan, maintainability is not of high importance.

== Quality Scenarios

[.helptext]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
